# .github/workflows/e2e.yml

name: E2E Tests

on:
  push:
    branches: [main]
  merge_group:

jobs:
  e2e-test:
    name: E2E Test - ${{ matrix.sandbox }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox: [sandbox:none, sandbox:docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Fix rollup platform dependency
        run: |
          # Explicitly install the platform-specific rollup package
          # This is a workaround for https://github.com/npm/cli/issues/4828
          npm install @rollup/rollup-linux-x64-gnu --no-save || true

      - name: Build project
        run: npm run build


      - name: Set up Docker
        if: matrix.sandbox == 'sandbox:docker'
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Set up Podman
        if: matrix.sandbox == 'sandbox:podman'
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run E2E tests
        env:
          # Use OpenRouter as a cost-effective alternative to Google's API
          OPENAI_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_BASE_URL: https://openrouter.ai/api/v1
          LLXPRT_DEFAULT_MODEL: google/gemini-flash-1.5-8b
          LLXPRT_DEFAULT_PROVIDER: openai
          # Also provide Gemini API key if available
          GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }}
          LLXPRT_SANDBOX: ${{ matrix.sandbox == 'sandbox:none' && 'false' || matrix.sandbox == 'sandbox:docker' && 'docker' || matrix.sandbox == 'sandbox:podman' && 'podman' }}
          VERBOSE: true
          DEBUG: true
        run: npm run test:integration:${{ matrix.sandbox }} -- --verbose --keep-output
